db/docker-compose.yml: set Compose file format version to 2.4
This fixes the following error:

	ERROR: The Compose file './docker-compose.yml' is invalid because:
	Unsupported config option for services.postgres: 'healthcheck'

Compose documentations states [1]:

	When specifying the Compose file version to use, make sure to specify
	both the major and minor numbers. If no minor version is given, 0 is
	used by default and not the latest minor version. As a result, features
	added in later versions will not be supported.

The healthcheck parameter was introduced in v2.1. Later, v2.3 added
start_period for healthchecks. Thus it seems sound to bump the format version
to the latest v2.

[1]: https://docs.docker.com/compose/compose-file/compose-versioning/#version-2